# Generated by Django 5.1.4 on 2025-04-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loggin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(choices=[('Employee', 'Employee'), ('Candidate', 'Candidate'), ('Examiner', 'Examiner'), ('Admin', 'Admin'), ('SME', 'SME')], max_length=50)),
                ('user_name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('Tech', 'Tech'), ('Quality Check', 'Quality Check'), ('Media', 'Media'), ('Business Development', 'Business Development')], max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('employee_id', models.CharField(max_length=20)),
                ('designation', models.CharField(choices=[('Developer', 'Developer'), ('Analyzer', 'Analyzer'), ('Business Development Executive', 'Business Development Executive')], max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('remarks1', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks2', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
